apiVersion: apps/v1
kind: Deployment
metadata:
  name: ven-web-app-prod-deployment
  labels:
    app: ven-web-app-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ven-web-app-prod
  template:
    metadata:
      labels:
        app: ven-web-app-prod
    spec:
      containers:
        - name: ven-web-app-prod
          image: venacraks.azurecr.io/vencapstoneproj:$(Build.BuildId)
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ven-web-app-prod-loadbalancer-service
  labels:
    app: ven-web-app-prod
spec:
  type: LoadBalancer
  selector:
    app: ven-web-app-prod
  ports:
    - port: 8084
      targetPort: 8080



